# Generated by Django 4.1.4 on 2023-02-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('turn', models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], max_length=5, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('board', models.JSONField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
