# Generated by Django 4.1.4 on 2023-02-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], max_length=5, null=True),
        ),
    ]
