# Generated by Django 4.1.4 on 2023-02-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='uuid',
            new_name='id',
        ),
    ]
