# Generated by Django 4.1.4 on 2023-02-18 08:23

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_black_game_white_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dice',
            field=models.JSONField(blank=True, default=game.models.DiceDefault, null=True),
        ),
    ]
