# Generated by Django 4.1.4 on 2023-02-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_dice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InGameMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
