# Generated by Django 4.1.4 on 2023-02-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_ingamemessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingamemessages',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
