# Generated by Django 4.1.4 on 2023-02-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_ingamemessages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingamemessages',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
