# Generated by Django 4.1.4 on 2023-02-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_ingamemessages_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dicePhysics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
