# Generated by Django 4.1.4 on 2023-03-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], default='black', max_length=5, null=True),
        ),
    ]
