# Generated by Django 4.1.4 on 2023-03-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_turn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='dicePhysics',
            new_name='dice_physics',
        ),
        migrations.AddField(
            model_name='game',
            name='player_timer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn',
            field=models.CharField(blank=True, choices=[('white', 'white'), ('black', 'black')], default='black', max_length=5, null=True),
        ),
    ]
