# Generated by Django 4.1.4 on 2023-05-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_ingamemessages_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingamemessages',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/messages'),
        ),
    ]
