# Generated by Django 4.1.4 on 2023-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_ingamemessages_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingamemessages',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/messages'),
        ),
    ]
