/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Igor Med (https://sketchfab.com/net_3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-rust-dice-36999c6522884aa395ec9a9dd5fe8069
title: [Free] Rust dice
No additional changes were made to this model.
*/
import { useGLTF } from "@react-three/drei"
import { MeshProps } from "@react-three/fiber"
import { GLTFResult } from "../../../game/types/GLTFResult.type"

const DiceRust = (props: MeshProps) => {
  const { nodes, materials } = useGLTF("/models/rust_dice.glb") as GLTFResult
  return (
    <mesh
      {...props}
      geometry={nodes.Object_2.geometry}
      material={materials.initialShadingGroup}
      receiveShadow
    />
  )
}

export default DiceRust

useGLTF.preload("/models/rust_dice.glb")
