# Generated by Django 4.1.4 on 2023-01-02 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pending_friend_requests',
            new_name='friend_requests',
        ),
    ]
