# Generated by Django 4.1.4 on 2023-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_pending_friend_requests_customuser_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
