# Generated by Django 4.1.4 on 2023-04-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rejected_request',
        ),
    ]
