# Generated by Django 4.1.4 on 2023-05-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_rejected_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.CharField(blank=True, choices=[('credentials', 'credentials'), ('discord', 'discord')], default='credentials', max_length=11),
        ),
    ]
