# Generated by Django 4.1.4 on 2023-02-07 04:41

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_chat_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game_requests',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('725e20a9-1620-487b-84a1-b448d6c55461'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
