# Generated by Django 4.1.4 on 2023-02-08 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_chat_uuid_alter_customuser_rejected_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('538f503a-fe53-4642-9101-891a1977a5fd'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
