# Generated by Django 4.1.4 on 2023-02-08 22:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_chat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a5b99c8e-b285-4fd6-8a52-77689b3d0954'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
