# Generated by Django 4.1.4 on 2023-02-08 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_chat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a6a8d27f-d35c-4c83-aa4a-1e5d947e7862'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
