# Generated by Django 4.1.4 on 2023-02-08 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_chat_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c3516390-f106-4d08-a026-e7f85a19af50'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
